import { math as commonMath_mathjs } from "./common/Math";
import { Vec2 as commonVec2_Vec2js } from "./common/Vec2";
import { Vec3 as commonVec3_Vec3js } from "./common/Vec3";
import { Mat22 as commonMat22_Mat22js } from "./common/Mat22";
import { Mat33 as commonMat33_Mat33js } from "./common/Mat33";
import { Transform as commonTransform_Transformjs } from "./common/Transform";
import { Rot as commonRot_Rotjs } from "./common/Rot";
import { AABB as collisionAABB_AABBjs } from "./collision/AABB";
import { Shape as Shape_Shapejs } from "./Shape";
import { Fixture as Fixture_Fixturejs } from "./Fixture";
import { Body as Body_Bodyjs } from "./Body";
import { Contact as Contact_Contactjs } from "./Contact";
import { Joint as Joint_Jointjs } from "./Joint";
import { World as World_Worldjs } from "./World";
import { CircleShape as shapeCircleShape_CircleShapejs } from "./shape/CircleShape";
import { EdgeShape as shapeEdgeShape_EdgeShapejs } from "./shape/EdgeShape";
import { PolygonShape as shapePolygonShape_PolygonShapejs } from "./shape/PolygonShape";
import { ChainShape as shapeChainShape_ChainShapejs } from "./shape/ChainShape";
import { BoxShape as shapeBoxShape_BoxShapejs } from "./shape/BoxShape";
import { CollidePolygons as shapeCollidePolygon_CollidePolygonsjs } from "./shape/CollidePolygon";
import { DistanceJoint as jointDistanceJoint_DistanceJointjs } from "./joint/DistanceJoint";
import { FrictionJoint as jointFrictionJoint_FrictionJointjs } from "./joint/FrictionJoint";
import { GearJoint as jointGearJoint_GearJointjs } from "./joint/GearJoint";
import { MotorJoint as jointMotorJoint_MotorJointjs } from "./joint/MotorJoint";
import { MouseJoint as jointMouseJoint_MouseJointjs } from "./joint/MouseJoint";
import { PrismaticJoint as jointPrismaticJoint_PrismaticJointjs } from "./joint/PrismaticJoint";
import { PulleyJoint as jointPulleyJoint_PulleyJointjs } from "./joint/PulleyJoint";
import { RevoluteJoint as jointRevoluteJoint_RevoluteJointjs } from "./joint/RevoluteJoint";
import { RopeJoint as jointRopeJoint_RopeJointjs } from "./joint/RopeJoint";
import { WeldJoint as jointWeldJoint_WeldJointjs } from "./joint/WeldJoint";
import { WheelJoint as jointWheelJoint_WheelJointjs } from "./joint/WheelJoint";
import { Sweep as commonSweep_Sweepjs } from "./common/Sweep";
import { toString as commonstats_toStringjs } from "./common/stats";
import { Manifold as Manifold_Manifoldjs } from "./Manifold";
import { Distance as collisionDistance_Distancejs } from "./collision/Distance";
import { TimeOfImpact as collisionTimeOfImpact_TimeOfImpactjs } from "./collision/TimeOfImpact";
import { DynamicTree as collisionDynamicTree_DynamicTreejs } from "./collision/DynamicTree";
import { Settings as Settings_Settingsjs } from "./Settings";
import "./shape/CollideCircle";
import "./shape/CollideEdgeCircle";
import "./shape/CollideCirclePolygone";
import "./shape/CollideEdgePolygon";
internal_internal = {};

Math_Math = commonMath_mathjs;
Vec2_Vec2 = commonVec2_Vec2js;
Vec3_Vec3 = commonVec3_Vec3js;
Mat22_Mat22 = commonMat22_Mat22js;
Mat33_Mat33 = commonMat33_Mat33js;
Transform_Transform = commonTransform_Transformjs;
Rot_Rot = commonRot_Rotjs;

AABB_AABB = collisionAABB_AABBjs;

Shape_Shape = Shape_Shapejs;
Fixture_Fixture = Fixture_Fixturejs;
Body_Body = Body_Bodyjs;
Contact_Contact = Contact_Contactjs;
Joint_Joint = Joint_Jointjs;
World_World = World_Worldjs;

Circle_Circle = shapeCircleShape_CircleShapejs;
Edge_Edge = shapeEdgeShape_EdgeShapejs;
Polygon_Polygon = shapePolygonShape_PolygonShapejs;
Chain_Chain = shapeChainShape_ChainShapejs;
Box_Box = shapeBoxShape_BoxShapejs;

internal_internal.CollidePolygons = shapeCollidePolygon_CollidePolygonsjs;

DistanceJoint_DistanceJoint = jointDistanceJoint_DistanceJointjs;
FrictionJoint_FrictionJoint = jointFrictionJoint_FrictionJointjs;
GearJoint_GearJoint = jointGearJoint_GearJointjs;
MotorJoint_MotorJoint = jointMotorJoint_MotorJointjs;
MouseJoint_MouseJoint = jointMouseJoint_MouseJointjs;
PrismaticJoint_PrismaticJoint = jointPrismaticJoint_PrismaticJointjs;
PulleyJoint_PulleyJoint = jointPulleyJoint_PulleyJointjs;
RevoluteJoint_RevoluteJoint = jointRevoluteJoint_RevoluteJointjs;
RopeJoint_RopeJoint = jointRopeJoint_RopeJointjs;
WeldJoint_WeldJoint = jointWeldJoint_WeldJointjs;
WheelJoint_WheelJoint = jointWheelJoint_WheelJointjs;

internal_internal.Sweep= commonSweep_Sweepjs;
internal_internal.stats = commonstats_toStringjs;
internal_internal.Manifold = Manifold_Manifoldjs;
internal_internal.Distance = collisionDistance_Distancejs;
internal_internal.TimeOfImpact = collisionTimeOfImpact_TimeOfImpactjs;
internal_internal.DynamicTree = collisionDynamicTree_DynamicTreejs;
internal_internal.Settings = Settings_Settingsjs;
var internal_internal;
export { internal_internal as internal };
var Math_Math;
export { Math_Math as Math };
var Vec2_Vec2;
export { Vec2_Vec2 as Vec2 };
var Vec3_Vec3;
export { Vec3_Vec3 as Vec3 };
var Mat22_Mat22;
export { Mat22_Mat22 as Mat22 };
var Mat33_Mat33;
export { Mat33_Mat33 as Mat33 };
var Transform_Transform;
export { Transform_Transform as Transform };
var Rot_Rot;
export { Rot_Rot as Rot };
var AABB_AABB;
export { AABB_AABB as AABB };
var Shape_Shape;
export { Shape_Shape as Shape };
var Fixture_Fixture;
export { Fixture_Fixture as Fixture };
var Body_Body;
export { Body_Body as Body };
var Contact_Contact;
export { Contact_Contact as Contact };
var Joint_Joint;
export { Joint_Joint as Joint };
var World_World;
export { World_World as World };
var Circle_Circle;
export { Circle_Circle as Circle };
var Edge_Edge;
export { Edge_Edge as Edge };
var Polygon_Polygon;
export { Polygon_Polygon as Polygon };
var Chain_Chain;
export { Chain_Chain as Chain };
var Box_Box;
export { Box_Box as Box };
var DistanceJoint_DistanceJoint;
export { DistanceJoint_DistanceJoint as DistanceJoint };
var FrictionJoint_FrictionJoint;
export { FrictionJoint_FrictionJoint as FrictionJoint };
var GearJoint_GearJoint;
export { GearJoint_GearJoint as GearJoint };
var MotorJoint_MotorJoint;
export { MotorJoint_MotorJoint as MotorJoint };
var MouseJoint_MouseJoint;
export { MouseJoint_MouseJoint as MouseJoint };
var PrismaticJoint_PrismaticJoint;
export { PrismaticJoint_PrismaticJoint as PrismaticJoint };
var PulleyJoint_PulleyJoint;
export { PulleyJoint_PulleyJoint as PulleyJoint };
var RevoluteJoint_RevoluteJoint;
export { RevoluteJoint_RevoluteJoint as RevoluteJoint };
var RopeJoint_RopeJoint;
export { RopeJoint_RopeJoint as RopeJoint };
var WeldJoint_WeldJoint;
export { WeldJoint_WeldJoint as WeldJoint };
var WheelJoint_WheelJoint;
export { WheelJoint_WheelJoint as WheelJoint };
